DROP TABLE IF EXISTS USERS;

CREATE TABLE USERS(
    id INT   PRIMARY KEY,
    userName    VARCHAR(250) NOT NULL
);

--Look in to FlyAway
INSERT INTO USERS VALUES (2,'David');
INSERT INTO USERS VALUES (3,'Felicia');